apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: 412914223877.dkr.ecr.ap-south-1.amazonaws.com/web-app:{{ .Values.image.tag }}
        imagePullPolicy: Always   # 👈 important
        ports:
        - containerPort: 8080
